spring.application.name=url-shortener

# Set root logging level to WARN (shows only WARN, ERROR, FATAL)
logging.level.root=WARN
# Optionally silence specific packages (e.g., Hibernate, Tomcat)
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.main.banner-mode=off

# Server
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eng3zim@gmail.com
spring.mail.password=euuvjcdisfrdvpij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.starttls.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT (custom)
application.jwt.secret=your-long-secret-key
application.jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Safe Browsing API
application.safebrowsing.key=AIzaSyB14bcoUMUzJhb6_drpSFzRuN-QZyBzLDQ
